// 自定义的u-chart 写在这里，外部调用。
import Vue from 'vue';

export default {
	// 饼图
	pieChart: (ctx, data, cWidth, cHeight) => {
		return {
			type: "ring",
			context: ctx,
			width: cWidth,
			height: cHeight,
			series: data.series,
			animation: true,
			timing: "easeOut",
			duration: 1000,
			rotate: false,
			rotateLock: false,
			background: "#FFFFFF",
			color: ["#1890FF", "#91CB74", "#FAC858", "#EE6666", "#73C0DE", "#3CA272", "#FC8452", "#9A60B4",
				"#ea7ccc"
			],
			padding: [5, 5, 5, 5],
			fontSize: 13,
			fontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
			dataLabel: true,
			dataPointShape: true,
			dataPointShapeType: "solid",
			touchMoveLimit: 60,
			enableScroll: false,
			enableMarkLine: false,
			legend: {
				show: true,
				position: "top",
				lineHeight: 25,
				float: "left",
				padding: 5,
				margin: 5,
				backgroundColor: "rgba(0,0,0,0)",
				borderColor: "rgba(0,0,0,0)",
				borderWidth: 0,
				fontSize: 13,
				fontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				hiddenColor: "#CECECE",
				itemGap: 10
			},
			// title: {
			//   name: "2,515억",
			//   fontSize: 15,
			//   color: "#666666",
			//   offsetX: 0,
			//   offsetY: 0
			// },
			// subtitle: {
			//   name: "자산총계",
			//   fontSize: 25,
			//   color: "#7cb5ec",
			//   offsetX: 0,
			//   offsetY: 0
			// },
			extra: {
				ring: {
					ringWidth: 30,
					activeOpacity: 0.5,
					activeRadius: 10,
					offsetAngle: 0,
					labelWidth: 15,
					border: true,
					borderWidth: 3,
					borderColor: "#FFFFFF",
					centerColor: "#FFFFFF",
					customRadius: 0,
					linearType: "none"
				},
				tooltip: {
					showBox: true,
					showArrow: true,
					showCategory: false,
					borderWidth: 0,
					borderRadius: 0,
					borderColor: "#000000",
					borderOpacity: 0.7,
					bgColor: "#000000",
					bgOpacity: 0.7,
					gridType: "solid",
					dashLength: 4,
					gridColor: "#CCCCCC",
					boxPadding: 3,
					fontSize: 13,
					lineHeight: 20,
					fontColor: "#FFFFFF",
					legendShow: true,
					legendShape: "auto",
					splitLine: true,
					horizentalLine: false,
					xAxisLabel: false,
					yAxisLabel: false,
					labelBgColor: "#FFFFFF",
					labelBgOpacity: 0.7,
					labelFontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				}
			}
		}
	},
	// 线图
	lineChart(ctx, data, cWidth, cHeight) {
		return {
			type: "line",
			context: ctx,
			width: cWidth,
			height: cHeight,
			categories: data.categories,
			series: data.series,
			animation: true,
			timing: "easeOut",
			duration: 1000,
			rotate: false,
			rotateLock: false,
			background: "#FFFFFF",
			color: ["#01B4D5", "#91CB74", "#FAC858", "#EE6666", "#73C0DE", "#3CA272", "#FC8452", "#9A60B4",
				"#ea7ccc"
			],
			padding: [15, 10, 0, 15],
			fontSize: 13,
			fontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
			dataLabel: true,
			dataPointShape: true,
			dataPointShapeType: "solid",
			touchMoveLimit: 60,
			enableScroll: false,
			enableMarkLine: false,
			legend: {
				show: false,
				position: "bottom",
				float: "center",
				padding: 5,
				margin: 5,
				backgroundColor: "rgba(0,0,0,0)",
				borderColor: "rgba(0,0,0,0)",
				borderWidth: 0,
				fontSize: 13,
				fontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				lineHeight: 11,
				hiddenColor: "#CECECE",
				itemGap: 10
			},
			xAxis: {
				disableGrid: true,
				disabled: false,
				axisLine: true,
				axisLineColor: "#CCCCCC",
				calibration: false,
				fontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				fontSize: 13,
				lineHeight: 20,
				marginTop: 0,
				rotateLabel: false,
				rotateAngle: 45,
				itemCount: 5,
				boundaryGap: "center",
				splitNumber: 5,
				gridColor: "#CCCCCC",
				gridType: "solid",
				dashLength: 4,
				gridEval: 1,
				scrollShow: false,
				scrollAlign: "left",
				scrollColor: "#A6A6A6",
				scrollBackgroundColor: "#EFEBEF",
				title: "",
				titleFontSize: 13,
				titleOffsetY: 0,
				titleOffsetX: 0,
				titleFontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				formatter: ""
			},
			yAxis: {
				gridType: "dash",
				dashLength: 2,
				disabled: false,
				disableGrid: false,
				splitNumber: 5,
				gridColor: "#CCCCCC",
				padding: 10,
				showTitle: false,
				data: []
			},
			extra: {
				line: {
					type: "straight",
					width: 2,
					activeType: "hollow",
					linearType: "none",
					onShadow: false,
					animation: "vertical"
				},
				tooltip: {
					showBox: true,
					showArrow: true,
					showCategory: false,
					borderWidth: 0,
					borderRadius: 0,
					borderColor: "#000000",
					borderOpacity: 0.7,
					bgColor: "#000000",
					bgOpacity: 0.7,
					gridType: "solid",
					dashLength: 4,
					gridColor: "#CCCCCC",
					boxPadding: 3,
					fontSize: 13,
					lineHeight: 20,
					fontColor: "#FFFFFF",
					legendShow: true,
					legendShape: "auto",
					splitLine: true,
					horizentalLine: false,
					xAxisLabel: false,
					yAxisLabel: false,
					labelBgColor: "#FFFFFF",
					labelBgOpacity: 0.7,
					labelFontColor: Vue.prototype.$theme.CHART_TEXT_COLOR,
				},
				markLine: {
					type: "solid",
					dashLength: 4,
					data: []
				}
			}
		};
	}
}